/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rpallerla' at '4/19/16 2:43 PM' with Gradle 2.12
 *
 * @author rpallerla, @date 4/19/16 2:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
